import { readFile, writeFile } from "node:fs/promises";
import { resolve } from "node:path";

export const ACTIVITY_START = "<!-- AUTO:ACTIVITY:START -->";
export const ACTIVITY_END = "<!-- AUTO:ACTIVITY:END -->";

function escapeCell(value) {
  return String(value).replaceAll("|", "\\|").replaceAll("\n", " ");
}

function badgeSegment(value) {
  return encodeURIComponent(String(value).replaceAll("-", "--").replaceAll("_", "__").replaceAll(" ", "_"));
}

function renderLinks(links) {
  return links.map((link) => {
    const logo = link.logo ? `&logo=${encodeURIComponent(link.logo)}&logoColor=white` : "";
    const image = `https://img.shields.io/badge/${badgeSegment(link.label)}-${badgeSegment(link.value)}-${link.color}?style=for-the-badge${logo}`;
    return `  <a href="${link.url}"><img alt="${link.label}" src="${image}"></a>`;
  }).join("\n");
}

function renderFocus(focus) {
  return [
    "| Area | What I am exploring |",
    "| --- | --- |",
    ...focus.map((item) => `| **${escapeCell(item.name)}** | ${escapeCell(item.description)} |`)
  ].join("\n");
}

function renderProjects(projects) {
  return [
    "| Project | Focus | Why it matters |",
    "| --- | --- | --- |",
    ...projects.map((project) => {
      const homepage = project.homepage ? ` [Live](${project.homepage})` : "";
      return `| [**${escapeCell(project.name)}**](${project.url}) | ${escapeCell(project.focus)} | ${escapeCell(project.summary)}${homepage} |`;
    })
  ].join("\n");
}

function extractActivity(readme) {
  const startIndex = readme.indexOf(ACTIVITY_START);
  const endIndex = readme.indexOf(ACTIVITY_END);
  if (startIndex === -1 || endIndex === -1 || endIndex <= startIndex) return null;
  return readme.slice(startIndex + ACTIVITY_START.length, endIndex).trim();
}

async function readExistingActivity(readmePath) {
  try {
    const existing = await readFile(readmePath, "utf8");
    return extractActivity(existing);
  } catch (error) {
    if (error.code === "ENOENT") return null;
    throw error;
  }
}

function renderTechBadges(techStack) {
  const mapping = {
    "typescript": { label: "TypeScript", logo: "typescript", logoColor: "60A5FA" },
    "react native": { label: "React Native", logo: "react", logoColor: "61DAFB" },
    "react": { label: "React", logo: "react", logoColor: "61DAFB" },
    "node.js": { label: "Node.js", logo: "nodedotjs", logoColor: "4ADE80" },
    "nodejs": { label: "Node.js", logo: "nodedotjs", logoColor: "4ADE80" },
    "python": { label: "Python", logo: "python", logoColor: "FACC15" },
    "kotlin": { label: "Kotlin", logo: "kotlin", logoColor: "A78BFA" },
    "postgresql": { label: "PostgreSQL", logo: "postgresql", logoColor: "93C5FD" },
    "sqlite": { label: "SQLite", logo: "sqlite", logoColor: "38BDF8" },
    "aes-256": { label: "AES-256", logo: "auth0", logoColor: "F87171" },
    "docker": { label: "Docker", logo: "docker", logoColor: "38BDF8" },
    "android": { label: "Android", logo: "android", logoColor: "4ADE80" },
    "rest apis": { label: "REST APIs", logo: "postman", logoColor: "F97316" },
    "rest api": { label: "REST API", logo: "postman", logoColor: "F97316" },
    "graphql": { label: "GraphQL", logo: "graphql", logoColor: "F472B6" }
  };

  return techStack.map((item) => {
    const key = item.toLowerCase().trim();
    const info = mapping[key] || { label: item, logo: "", logoColor: "white" };
    const logoParam = info.logo ? `&logo=${info.logo}&logoColor=${info.logoColor}` : "";
    const labelSegment = encodeURIComponent(info.label).replaceAll("-", "--").replaceAll("_", "__");
    return `![${info.label}](https://img.shields.io/badge/${labelSegment}-1E293B?style=flat-square${logoParam})`;
  }).join(" ");
}

export async function generateProfileReadme({ config, manifest, readmePath }) {
  const existingActivity = await readExistingActivity(readmePath);
  const activity = existingActivity || "_Recent public activity will appear here after the workflow runs._";
  const activitySection = config.activity.enabled
    ? `\n## Recent Activity\n\n${ACTIVITY_START}\n${activity}\n${ACTIVITY_END}\n`
    : "";
  const techStack = renderTechBadges(config.techStack);
  const about = config.profile.about.join("\n\n");

  const readme = `<!-- Generated by GitHub Profile Agent Console. Edit profile.config.json, then run npm run generate. -->
<p align="center">
  <picture>
    <source media="(max-width: 760px) and (prefers-color-scheme: dark)" srcset="./assets/hero/${manifest.assets.mobileDark}">
    <source media="(max-width: 760px)" srcset="./assets/hero/${manifest.assets.mobileLight}">
    <source media="(prefers-color-scheme: dark)" srcset="./assets/hero/${manifest.assets.desktopDark}">
    <source media="(prefers-color-scheme: light)" srcset="./assets/hero/${manifest.assets.desktopLight}">
    <img src="./assets/hero/${manifest.assets.desktopDark}" alt="${config.profile.name} - ${config.profile.headline}" width="100%">
  </picture>
</p>

<p align="center">
${renderLinks(config.links)}
</p>

## About Me

${about}

## Current Focus

${renderFocus(config.focus)}

## Featured Work

${renderProjects(config.projects)}

## Research Direction

${config.research.narrative}

## Tech Stack

${techStack}
${activitySection}
---

<p align="center">
  ${config.footer}
</p>
`;

  await writeFile(resolve(readmePath), readme);
  return readme;
}
